services:
  # chromadb:
  #   image: chromadb/chroma:0.6.3
  #   volumes:
  #     - ./chromadb:/chroma/chroma
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - net

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

