services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  postgres:
    image: timescale/timescaledb-ha:pg17
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data:/home/postgres/pgdata/data
    command: [ "-c", "ai.ollama_host=http://ollama:11434" ]
    env_file:
      - .env
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest     
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
    depends_on:
      - postgres
    env_file:
      - .env
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    

  maildev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.maildev
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped

networks:
  net:
    driver: bridge

volumes:
  data:
